const mongoose = require('mongoose')
const PropertySchema= new mongoose.Schema({
    houseOwner:{
        type:String
    },
    houseAddress:{
        type:String
    },
    housePrice:{
        type:Number
    },
    houseLoan:{
       type:Number,
       default:0

    },
    flatOwner:{
        type:String
    },
    flatAddress:{
        type:String
    },
    flatType:{
        type:String
    },
    flatPrice:{
        type:Number
    },
    flatLoan:{
        type:Number,
        default:0
    },
    landOwner:{
        type:String
    },
    landAddress:{
        type:String
    },
    landPrice:{
        type:Number
    },
    landLoan:{
        type:Number,
        default:0
    },
    farmingOwner:{
        type:String
    },
    farmingAddress:{
        type:String
    },
    farmingPrice:{
        type:Number
    },
    farmingLoan:{
        type:Number,
        default:0
    },
    shopOwner:{
        type:String
    },
    shopAddress:{
        type:String
    },
    shopPrice:{
        type:Number
    },
    shopLoan:{
        type:Number,
        default:0
    },
    other:{
        type:String
    },
})
module.exports = mongoose.model('Property',PropertySchema)